####################################################

# https://leetcode.com/problems/fizz-buzz/

#Task:
#Write a program that outputs the string representation of numbers from 1 to n.
#But for multiples of three it should output “Fizz” instead of the number and for the multiples of five output “Buzz”. For numbers which are multiples of both three and five output “FizzBuzz”.

class Solution:
    def fizzBuzz(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        if i % 3 == 0 and i % 5 == 0:
            print ("Fizz Buzz")
        elif i % 5 == 0:
            print ("Buzz")
        elif i % 3 == 0:
            print ("Fizz")
        else:
            print(i)
			

####################################################

# https://leetcode.com/problems/sum-of-two-integers/

#Calculate the sum of two integers a and b, but you are not allowed to use the operator + and -.

class Solution:
    def getSum(self, a, b):
        """
        :type a: int
        :type b: int
        :rtype: int
        """
        if a == -b:
            return 0
        if abs(a) > abs(b):
            a, b = b, a
        if a < 0:
            return -self.getSum(-a, -b)
        while b:
            c = a & b
            a ^= b
            b = c << 1
        return a

		
####################################################
	
# https://leetcode.com/problems/find-the-difference/

#Given two strings s and t which consist of only lowercase letters.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Find the letter that was added in t.

def findTheDifference(self, s, t):
    s_sorted = sorted(list(s))
    t_sorted = sorted(list(t))
    for i in range(len(s)):
        if s_sorted[i] != t_sorted[i]:
            return t_sorted[i]
    return t_sorted[-1]